name: Deploy to GitHub Pages

on:
  push:
    branches: [main]        # or master, depending on your default branch
  workflow_dispatch:        # allows manual trigger

permissions:
  contents: write           # required to push to gh-pages

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 24
          cache: 'npm'          # optional, but speeds up installs (requires lock file)

      - name: Install dependencies
        run: npm install        # works without a lock file

      - name: Build project
        run: npm run build
        
      - name: Build project
        run: npm run preview       

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          publish_branch: gh-pages
